# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  branches:
   include:
     - main
 
pr: none

pool:
  vmImage: ubuntu-latest

steps: 
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
- script: |
      npm run create -- --widgetname=testwidget
      npm run packall
  displayName: Create and Packall
- bash: ls -R $(System.DefaultWorkingDirectory)

- task: S3Upload@1
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
  inputs:
    awsCredentials: 'Aws access'
    regionName: 'us-east-2'
    bucketName: $(s3-bucket-name)
    sourceFolder: $(sourceFolder)
    filesAcl: 'public-read'
    targetFolder: $(targetFolder)

- task: AWSCLI@1
  displayName: 'Invalidate CloudFront Cache'
  inputs:
    awsCredentials: 'Aws access'
    regionName: 'us-east-2'
    awsCommand: 'cloudfront'
    awsSubCommand: 'create-invalidation'
    awsArguments: '--distribution-id $(distributionID) --paths $(CacheclearPath)'
