# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
- script: |
      npm run create -- --widgetname=testwidget
      npm run packall
  displayName: Create and Packall
- bash: ls -R $(System.DefaultWorkingDirectory)
# - script: |
#     echo "s3-bucket-name"
#     $(s3-bucket-name)
    
- task: S3Upload@1
  inputs:
    awsCredentials: 'Aws access'
    regionName: 'us-east-2'
    bucketName: $(s3-bucket-name)
    sourceFolder: '$(System.DefaultWorkingDirectory)/dist'
    targetFolder: wp/custom-widgets/
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
    artifactName: 'distFiles'